apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- range .Values.ingress.paths }}
      - pathType: {{ .pathType }}
        path: "{{ .path }}"
        backend:
          service:
            name: {{ include (printf "%s.fullname" .serviceName) $ }}-{{ .serviceName }}
            port:
              number: {{ .servicePort }}
      {{- end }}