apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/content"
        backend:
          service:
            name: {{ include "cms.fullname" . }}-knotx
            port:
              number: {{ .Values.knotx.service.port }}
      - pathType: ImplementationSpecific
        path: "/api"
        backend:
          service:
            name: {{ include "cms.fullname" . }}-knotx
            port:
              number: {{ .Values.knotx.service.port }}
      - pathType: ImplementationSpecific
        path: "/assets"
        backend:
          service:
            name: {{ include "dam.fullname" . }}-dam
            port:
              number: {{ .Values.dam.service.port }}