replicaCount: 1

image:
  repository: handsonarchitects/knotx-demo-application
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: 127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
