name: 'Test: Verify deployment'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-deployment:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout codebase'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Setup Gradle'
      uses: gradle/actions/setup-gradle@v3

    - name: 'Build Docker image'
      run: ./application/code/gradlew -p ./application/code build-docker --info

    - name: 'Setup Helm'
      uses: azure/setup-helm@v4.1.0
      with:
        version: v3.13.3

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.9'

    - name: Setup Kind
      run: go install sigs.k8s.io/kind@v0.22.0

    - name: Create K8s cluster
      run: kind create cluster --config .github/kind.yaml

    - name: Install Ingress Controller
      run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

    - name: Load Docker image in Kind
      run: kind load docker-image handsonarchitects/knotx-demo-application

    - name: Wait for Ingress Controller
      run: kubectl -n ingress-nginx rollout status deployment ingress-nginx-controller

    - name: Create pdp namespace
      run: kubectl create namespace pdp

    - name: Install pdp example
      run: helm -n pdp install pdp ./examples/pdp

    - name: Wait for pdp example
      run:
        kubectl -n pdp rollout status deployment
    
    - name: Check API
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: curl -i http://demo.127.0.0.1.nip.io/api/v1/example | grep "HTTP/1.1 200"

    - name: Check page
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: curl -i http://demo.127.0.0.1.nip.io/content/index.html | grep "HTTP/1.1 200"

    - name: Check assets
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: curl -i http://demo.127.0.0.1.nip.io/assets/knotx-logo.png | grep "HTTP/1.1 200"
